### ISSUE TITLE
Should I first talk about IVPs or OCPs?

### ISSUE THREAD

**Issue by mzanon** [mzanon/thesis#3]
After introducing dynamic systems, should I directly talk about simulating them or should I wait until I mention optimal control and NLPs, so that it is clear that I also need the sensitivities?

**Comment by rienq** [comment]
I would say first IVPs.. then the discretization procedure for multiple shooting can be defined in a very clean way:
you can define a function \phi(x_k,u_k) which provides us with a numerical approximation of the solution of the IVP you defined before, no?

**Comment by mzanon** [comment]
Sure I also thought about that, but then what about sensitivities? It is definitely easier to explain them once you say why you need them...

**Comment by rienq** [comment]
yea, sensitivities are not really part of IVPs right? They are not even mentioned in most books about simulation..

**Comment by mzanon** [comment]
sure, but I am also not interested in IVPs without considering sensitivities...

**Comment by rienq** [comment]
What about introducing the IVP but not anything on how to solve them, so you can leave numerical simulation and sensitivities for later?

**Comment by mzanon** [comment]
good point!

**Comment by rienq** [comment]
:+1:
